### ISSUE TITLE
Unprocessed note

### ISSUE THREAD

**Issue by eserte** [flohoff/noteisdue#1]
https://www.openstreetmap.org/note/4409690 was not processed by noteisdue

(Just as a reminder, you added me to the list of users, see https://community.openstreetmap.org/t/gesperrte-brucke-eingetragen-wird-das-in-osm-nicht-angezeigt-wenn-nicht-im-edit-mode/112206/11 and I vaguely remember that it worked at least once)

**Comment by flohoff** [comment]
Spannend - den hat die software gesehen und in die Datenbank eingetragen:

` 1067 | 2024-09-02 23:08:10.599358 | 4409690 | 2025-04-30 00:00:00 | f        | 2024-09-02 23:06:40 | reopen | eserte`

Ahhh - vermutlich ist das das oauth1/oauth2 login issue der OSM API - Der hat den note vermutlich nicht geschlossen bekommen. 

Ich glaube ich muss da nochmal dran ...

**Comment by flohoff** [comment]
Also - dein note ist jetzt vom "flohoff" geschlossen worden. Das war noch eine issue das ich einen oauth2 token mit dem falschen user erzeugt habe. 

Aber - OAuth2 authentication geht jetzt und noteisdue sollte wieder normal laufen.

3d4c36793486ff306b24ffce3676f3bed65d4dcd
